"""mensagem da migration

Revision ID: 132f15b699ed
Revises: 
Create Date: 2025-05-25 18:19:56.968967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132f15b699ed'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover ENUM duplicado se existir
    op.execute('DROP TYPE IF EXISTS accesslevel;')
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###