"""Added new migrations

Revision ID: 5c4e3191e6fb
Revises: 7d030ac69ca4
Create Date: 2025-05-25 20:16:21.073789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4e3191e6fb'
down_revision = '7d030ac69ca4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###