"""Added new migrations

Revision ID: 7d030ac69ca4
Revises: a8330f476a14
Create Date: 2025-05-25 18:39:05.479771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d030ac69ca4'
down_revision = 'a8330f476a14'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###