"""Added new migrations

Revision ID: eacca904a765
Revises: 132f15b699ed
Create Date: 2025-05-25 18:21:13.411434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacca904a765'
down_revision = '132f15b699ed'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###